global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['192.168.1.4:9182']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.4:8080']